spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hiber
    password: 1234
    driver-class-name: org.postgresql.Driver
    username: alex
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
